main:
- name: "Services"
  url: "/services/"
  weight: 1
- name: "Work"
  url: "/work/"
  weight: 2
- name: "About"
  url: "/about/"
  weight: 3
- name: "History"
  url: "/history/"
  weight: 3
- name: "Contact"
  url: "/contact/"
  weight: 4
